// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt (args[0]);
		int countGreaterToHalf =0;// count of random numbers greater than 0.5
		int countLessOrEqualToHalf =0;// count of random numbers less than or equal to 0.5
		// Generate n random numbers and count how many are greater than 0.5 and how many are less than or equal to 0.5
	    for (int i=0 ; i<n ; i++) {
			double r = Math.random();
			if (r > 0.5) {
				countGreaterToHalf=countGreaterToHalf+1;
			} else {
				countLessOrEqualToHalf=countLessOrEqualToHalf+1;
			}
	}
	// Print the results
	System.out.println(">0/5: " + countGreaterToHalf + " times");
	System.out.println("<=0.5: " + countLessOrEqualToHalf + " times");
	// Print the ratio only if both counts are non-zero to avoid division by zero
	if (countGreaterToHalf != 0 && countLessOrEqualToHalf != 0) {
		if (countGreaterToHalf <= countLessOrEqualToHalf) {
		double ratio = (double)countGreaterToHalf / (double)countLessOrEqualToHalf;
		System.out.println("Ratio: " + ratio);
	} else {
		double ratio = (double)countLessOrEqualToHalf / (double)countGreaterToHalf;
		System.out.println("Ratio: " + ratio);
	}
	}
  }
}
